# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title General symmetric map
#' @name gensymMap_cpp
#' @description a generalization of a one dimensional map, which incorporates (among others) the lorenz-, logistic and cubeMap
#' @param x input value for one iteration
#' @param r control parameter
#' @param alpha exponent
#' @return The result of one single iteration/
#' @author J.C. Lemm, P.v.W. Crommelin
#' @references S. Sprott, Chaos and Time-series analysis
#'
NULL

#' @export
gensymMap_cpp <- function(x, r, alpha) {
    .Call(`_myBayes_gensymMap_cpp`, x, r, alpha)
}

#' @export
gsm_iter_cpp <- function(N, x0, r, alpha, N_discr, skipFirst) {
    .Call(`_myBayes_gsm_iter_cpp`, N, x0, r, alpha, N_discr, skipFirst)
}

