#' @export
simplePlot = function(main="simplePlot",
                      x = NULL,
                      y = NULL,
                      xlim = NULL,
                      ylim = NULL,
                      xlab = "x",
                      ylab = "y",
                      col = "black",
                      bg = NULL,
                      type = "l",
                      sub = NULL,
                      col.axis = COLOR_AXIS,
                      col.lab = NULL,
                      col.main = NULL,
                      col.sub = NULL,
                      fg = COLOR_AXIS,
                      pch = 16,
                      cex = 1,
                      log = "",
                      leg = NULL,
                      position_leg = "topleft",
                      inset_leg = 0.05,
                      col_leg = NULL,
                      lty_leg = 1,
                      lwd_leg = 2,
                      title_leg = NULL,
                      bg_leg = COLOR_BG_LEG,
                      nx_grid = NX_GRID,
                      ny_grid = NY_GRID,
                      col_grid = COLOR_GRID,
                      lty_grid = POINTS,
                      lwd_grid = LWD_GRID,
                      las = NULL){
  plot(main = main,
       sub = sub,
       x = x,
       y = y,
       xlab = xlab,
       ylab = ylab,
       col = col,
       type = type,
       bg = bg,
       xlim = xlim,
       ylim = ylim,
       col.axis = col.axis,
       col.lab = col.lab,
       col.main = col.main,
       col.sub = col.sub,
       fg = fg,
       pch = pch,
       cex = cex,
       log = log,
       las = las)
  #grid(nx = NX_GRID,
  #     ny = NY_GRID,
  #     col = COLOR_GRID,
  #     lty = POINTS,
  #     lwd = LWD_GRID,
  #     equilogs = TRUE)
  grid()

  if (!is.null(leg)) {
    legend(position_leg,
           inset = inset_leg,
           legend = leg,
           col = col_leg,
           lty = lty_leg,
           lwd = lwd_leg,
           title = title_leg,
           bg = bg_leg)
  }
}
